# Generated by Django 4.0.4 on 2022-05-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedapp", "0005_queryrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="post",
        ),
        migrations.RemoveField(
            model_name="report",
            name="reported_by",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
