name: CI

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "*"

jobs:
  ci-run:
    name: Run integration tests
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: "ubuntu-latest"

    env:
      CI: 1
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}
      API_SERVER_PORT: 8002
      STREAM_SERVER_PORT: 8001
      PROJECTS_BASE: ".."

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"

      - name: Fetch hulse-py & api-server
        run: |
          cd ..
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/hulsedev/api-server.git 
          cd api-server && git checkout origin/setup-integration-tests && cd .. # temporary line
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/hulsedev/hulse-py.git
          cd hulse-py && git checkout origin/pipeline-wrapper && cd .. # temporary line
          cd stream-server/

      - name: Run integration tests
        run: |
          bash scripts/start-docker-postgres.sh
          sleep 5 # wait for postgres to start
          bash scripts/run-ci-integration-tests.sh api-server stream-server hulse-py
