name: CI

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "*"

jobs:
  ci-run:
    name: Run integration tests
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: "ubuntu-latest"

    env:
      CI: 1
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"

      - name: Fetch hulse-py & api-server
        shell: bash -l {0}
        run: |
          cd ..
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/hulsedev/api-server.git 
          cd api-server && git checkout origin/setup-integration-tests && cd .. # temporary line
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/hulsedev/hulse-py.git
          cd stream-server/

      - name: Fetching stream server
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ourcompany/whateverrepo
          path: whateverrepo

      - name: Run integration tests
        shell: bash -l {0}
        run: |
          bash scripts/start-docker-postgres.sh
          sleep 5 # wait for postgres to start
          bash scripts/run-ci-integration-tests.sh api-server stream-server hulse-py
        env:
          API_SERVER_PORT: 8002
          STREAM_SERVER_PORT: 8001
          PROJECTS_BASE: "../"
